spring:
  profiles:
    active: prd

cors:
  allowed-origins:
    - ENC(fk4Vi93ycKzKO7Ep6ZiPmZPpTACsnrzcQ2UP/JU2QKMX68LR+s0SJHa1nKagz78C)
    - ENC(x3A/Sn0ChzuYal0syhvhvw7a0O4+Lnh7QTtrNPZSy8sNaWd88ERZvA==)

# jasypt 암복호화
jasypt:
  encryptor:
    # JasyptConfig에 정의한 빈 이름
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )