spring:
  profiles:
    active: local

cors:
  allowed-origins:
    - ENC(2MEs9L/78BcUOxDONrByxKwOjok8JI6Ut+wJmUiDNNQ=)
    - ENC(KgR47MHoW+1bgKfRvDlp3S5CmUUWv2LKixKlPqe2tAc=)

# jasypt 암복호화
jasypt:
  encryptor:
    # JasyptConfig에 정의한 빈 이름
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )